#spring:
#  datasource:
#    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_1eb973b559fad20
#    username: b2958561bbea94
#    password: 88a5c940
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
spring:
  datasource:
    url: jdbc:postgresql://dpg-chim0im4dad01anahmhg-a.oregon-postgres.render.com:5432/easybook
    username: easybook
    password: 704JtcUKoIGL3UuN4MyNkVwagPnQ8RGL
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto:  update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: amoz4christ@gmail.com
    password: bbyswiazoqyjbtlc
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  email: amoz4christ@gmail.com
