spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_1eb973b559fad20
    username: b2958561bbea94
    password: 88a5c940
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: amoz4christ@gmail.com
    password: bbyswiazoqyjbtlc
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  email: amoz4christ@gmail.com

springdoc:
  swagger-ui:
    path=/swagger-ui:
      html: /api/v1/auth/swagger