
server:
  port:8081

spring:
  profiles:
    active: dev
  application:
    name: easybook-api
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  file:
    name: logs/${spring.application.name}.log

api:
  info:
    title: EasyBook API
    description: API for the easy book invoicing system
    version: 1.0

springdoc:
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui
  show-actuator: true

invoice:
  reminder:
    interval: '-'
#    interval: '0 0 0 * * ?'
