#spring:
#  datasource:
#    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_1eb973b559fad20
#    username: b2958561bbea94
#    password: 88a5c940
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
spring:
  datasource:
    url: jdbc:postgresql://dpg-clcfagug1b2c73eui510-a.oregon-postgres.render.com:5432/easybook_490c
    username: easybook
    password: 01WvDXTHWnjdBjLelmdQPFbwFEZEho0Z
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: server36.web-hosting.com
    port: 465
    username: EazyBook@softwareengineertechnology.co.uk
    password: isiminO28
    #    username: amoz4christ@gmail.com
#    password: kawyhdntddbpbgil
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

app:
  email: eazybook@softwareengineertechnology.co.uk
#  email: amoz4christ@gmail.com
