spring:
  datasource:
    url: postgres://rcafhpxexrdimy:ec2-54-157-79-121.compute-1.amazonaws.com:5432/d5bg8dbli5j01q
#    jdbc:mysql://localhost:3306/easybookdb
    username: rcafhpxexrdimy
    password: a773f1767d5b0e5e890e67cd89c275d1b7791ee3fa71062b389177fc6e9f0638
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

app:
  email: amoz4christ@gmail.com

springdoc:
  swagger-ui:
    path=/swagger-ui:
      html: /api/v1/auth/swagger